export enum ResponseCodeEnum {
    NOT_FOUND = 'NOT_FOUND',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    BAD_REQUEST = 'BAD_REQUEST',
    NOT_FOUND_CONTENT = 'NOT_FOUND_CONTENT',

    AUTH_FAILED = 'AUTH_FAILED',
    REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
    OLD_PASSWORD_IS_CORRECT = 'OLD_PASSWORD_IS_CORRECT',
    WRONG_DATA = 'WRONG_DATA',
    EMPLOYEE_CANT_VIEW_STORE = 'EMPLOYEE_CANT_VIEW_STORE',
    REQUIRE_ANSWER = 'REQUIRE_ANSWER',
    NEED_CHOOSE_ONLY_ONE_ANSWER = 'NEED_CHOOSE_ONLY_ONE_ANSWER',
    NEED_CHOOSE_FILE = 'NEED_CHOOSE_FILE',
    NEED_COMMENT = 'NEED_COMMENT',
    PASSWORD_WRONG = 'PASSWORD_WRONG',
    ANSWER_EXISTS_BY_SHOP = 'ANSWER_EXISTS_BY_SHOP'
}

const CODE_MESSAGES: { [key in ResponseCodeEnum]: string } = {
    NOT_FOUND: '該当のデータが見つかりません。',
    INTERNAL_SERVER_ERROR: '内部サーバーエラー',
    UNAUTHORIZED: 'アクセスが許可されていません',
    FORBIDDEN: 'アクセスは禁止されています。',
    BAD_REQUEST: '不正なリクエストメッセージです。',

    AUTH_FAILED: '正しいユーザーID・パスワードを入力して下さい。',
    REFRESH_TOKEN_INVALID: 'リフレッシュトークンが不正です。',
    OLD_PASSWORD_IS_CORRECT: '旧パスワードが正しくありません。',
    WRONG_DATA: 'ファイルの全データが不正です。',
    EMPLOYEE_CANT_VIEW_STORE: 'EMPLOYEE_CANT_VIEW_STORE',
    REQUIRE_ANSWER: 'REQUIRE_ANSWER',
    NEED_CHOOSE_ONLY_ONE_ANSWER: 'NEED_CHOOSE_ONLY_ONE_ANSWER',
    NEED_CHOOSE_FILE: 'NEED_CHOOSE_FILE',
    NEED_COMMENT: 'NEED_COMMENT',
    PASSWORD_WRONG : '現在のパスワードは正しくありません',
    ANSWER_EXISTS_BY_SHOP: 'ANSWER_EXISTS_BY_SHOP',
    NOT_FOUND_CONTENT : 'このコンテンツが現時点閲覧できません',
};

export const getMessage = (code: ResponseCodeEnum): string => {
    return CODE_MESSAGES[code];
};
