export enum TableEnum {
    USER = 'm_user',
    USER_TOKEN = 'm_user_token',
    USER_DEVICE = 'm_user_device',
    M_CHANNEL = 'm_channel',
    WK_SHOP = 'wk_shop',
    CONTENT = 'm_contents',
    D_QUESTIONNAIRE_RESPONSES = 'd_questionnaire_responses',
    D_QUESTIONNAIRE_QUESTION = 'd_questionnaire_question',
    M_QUESTIONNAIRE = 'm_questionnaire',
    D_NEW_INFORMATION = 'd_new_information',
    D_ORDER_PASSWORD = 'd_order_password',
    M_PROGRAM = 'm_program',
    D_REFERENCE_NUMBER = 'd_reference_number',
    D_CONTENTS_ROLE = 'd_contents_role',
    M_ROLE = 'm_role',
    M_GENERAL = 'm_general',
    M_DISTRIBUTION = 'm_distribution',
    D_DELIVERY_SHOP = 'd_delivery_shop',
    MST_MEISYO = 'mst_meisyo',
    M_ENTRYFORM = 'm_entryform',
    D_ENTRYFORM_RESPONSES = 'd_entryform_responses',
    M_URL = 'm_url',
    MST_TORI = 'mst_tori',
    TOKEN_ROCKETCHAT = 'token_rocketchat',
    MENU = 'menu',
}

export enum ViewEnum {
    V_USER_INFORMATION = 'v_user_information',
    V_USER_SHOP = 'v_user_shop',
    V_USER_CONTENTS = 'v_user_contents',
    V_USER_CONTENTS_SIMPLE = 'v_user_contents_simple',
}
